name: Python package

on: [push, pull_request]

jobs:
  build:

    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10", "3.11"]
        # use Ubuntu 20.04 for Python 3.6
        exclude:
        - os: "ubuntu-latest"
          python-version: "3.6"
        include:
        - os: "ubuntu-20.04"
          python-version: "3.6"


    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
      # there are currently no dependencies
        #  pip install -r requirements.txt
    - name: Install flake8
      run: pip install flake8
    - name: Lint with flake8
      run: |
        # stop the build if flake reports any issues
        flake8 . --statistics --show-source
    - name: Install pytest
      run: pip install pytest pytest-timeout
    - name: Test with pytest
      run: pytest --run-integration-tests
